spring.application.name=SGC

spring.datasource.url=jdbc:postgresql://localhost:5432/condominio_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=SGC_SUPER_SECRET_KEY_2026_COMPRIDA_E_SEGURA_1234567890
jwt.expiration=86400000
jwt.refresh-expiration=604800000
